import Foundation

nonisolated enum CubeLUTExporter {
    static let dimension = 33

    static func createFile(settings: GradeSettings, name: String) throws -> URL {
        let displayName = normalizedDisplayName(name)
        let samples = ImageRenderer.gradeCubeSamples(settings: settings, dimension: dimension)
        guard samples.count == dimension * dimension * dimension,
              samples.allSatisfy({ $0.x.isFinite && $0.y.isFinite && $0.z.isFinite }) else {
            throw CubeLUTError.invalidColorTransform
        }

        var cube = "# Generated by Hibiscus\n"
        cube += "TITLE \"\(escapedTitle(displayName))\"\n"
        cube += "LUT_3D_SIZE \(dimension)\n"
        cube += "DOMAIN_MIN 0.000000 0.000000 0.000000\n"
        cube += "DOMAIN_MAX 1.000000 1.000000 1.000000\n\n"
        cube.reserveCapacity(cube.count + samples.count * 30)

        let locale = Locale(identifier: "en_US_POSIX")
        for sample in samples {
            cube += String(
                format: "%.6f %.6f %.6f\n",
                locale: locale,
                clamped(sample.x),
                clamped(sample.y),
                clamped(sample.z)
            )
        }

        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("Hibiscus-LUT-\(UUID().uuidString)", isDirectory: true)
        do {
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            let fileURL = directory.appendingPathComponent(safeFilename(displayName)).appendingPathExtension("cube")
            guard let data = cube.data(using: .utf8) else { throw CubeLUTError.encodingFailed }
            try data.write(to: fileURL, options: .atomic)
            return fileURL
        } catch {
            try? FileManager.default.removeItem(at: directory)
            throw error
        }
    }

    static func removeTemporaryFile(at url: URL) {
        try? FileManager.default.removeItem(at: url.deletingLastPathComponent())
    }

    private static func normalizedDisplayName(_ name: String) -> String {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? "Hibiscus LUT" : trimmed
    }

    private static func escapedTitle(_ name: String) -> String {
        name.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
    }

    private static func safeFilename(_ name: String) -> String {
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_ "))
        let scalars = name.unicodeScalars.map { allowed.contains($0) ? Character(String($0)) : "-" }
        let sanitized = String(scalars)
            .split(whereSeparator: { $0 == " " || $0 == "-" })
            .filter { !$0.isEmpty }
            .joined(separator: "-")
        return sanitized.isEmpty ? "Hibiscus-LUT" : sanitized
    }

    private static func clamped(_ value: Float) -> Double {
        Double(min(1, max(0, value)))
    }
}

nonisolated private enum CubeLUTError: Error {
    case invalidColorTransform
    case encodingFailed
}
